# Generated by Django 5.2.1 on 2025-05-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_formation_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
