# Generated by Django 5.2.1 on 2025-05-08 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_formation_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenu',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='contenu',
            name='module',
        ),
        migrations.AddField(
            model_name='contenu',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contenu',
            name='formation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contenus', to='myapp.formation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contenu',
            name='fichier',
            field=models.FileField(blank=True, upload_to='contenus/'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='date_creation',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_complete', models.BooleanField(default=False)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.apprenant')),
                ('contenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.contenu')),
            ],
        ),
    ]
