# Generated by Django 5.2 on 2025-05-19 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_contenu_checked_remove_contenu_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptionsprogress',
            name='date_inscription',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='ContenuQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('fichier', models.FileField(blank=True, null=True, upload_to='contenus/')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizz_contenus', to='myapp.formation')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('reponse_correcte', models.CharField(max_length=255)),
                ('choix_1', models.CharField(max_length=255)),
                ('choix_2', models.CharField(max_length=255)),
                ('choix_3', models.CharField(max_length=255)),
                ('contenu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='myapp.contenuquiz')),
            ],
        ),
    ]
