# Generated by Django 5.2 on 2025-05-19 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_inscriptionsprogress_date_inscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizz', to='myapp.formation'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='contenu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='myapp.contenuquiz'),
        ),
        migrations.CreateModel(
            name='QuestionQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('bonne_reponse', models.CharField(max_length=255)),
                ('mauvaise_reponse1', models.CharField(max_length=255)),
                ('mauvaise_reponse2', models.CharField(max_length=255)),
                ('mauvaise_reponse3', models.CharField(max_length=255)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='myapp.contenuquiz')),
            ],
        ),
    ]
