# Generated by Django 5.2 on 2025-05-20 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_quiz_formation_alter_quiz_contenu_questionquiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='contenu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='myapp.contenu'),
        ),
        migrations.RemoveField(
            model_name='questionquiz',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='formation',
        ),
        migrations.AddField(
            model_name='contenu',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contenu',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='contenus/'),
        ),
        migrations.DeleteModel(
            name='ContenuQuiz',
        ),
        migrations.DeleteModel(
            name='QuestionQuiz',
        ),
    ]
