# Generated by Django 5.2 on 2025-05-22 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='contenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizz', to='myapp.contenu'),
        ),
    ]
